---
title: "Trabajo4TAE"
author: "Jhonier Santiago Serna Cardona"
date: "4/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library("readxl")
datos <- read_excel("archivos/registros_autos_entrenamiento.xlsx")
```

```{r}
##Creamos variable año, mes y dia.
fechas <- as.Date(datos$Fecha)
datos$anio <- as.numeric(format(fechas,format = "%Y"))
datos$mes <- as.numeric(format(fechas,format = "%m"))
datos$dia <- as.numeric(format(fechas,format = "%d"))
```

```{r message=FALSE, warning=FALSE}
##Pegando variables M1, M2 y M3 de los depósitos del sistema financiero.
library(dplyr)
library(tidyverse)
library(lubridate)

depositos <- read_excel("archivos/Depositos_Sistema_Financiero.xlsx", skip = 8)
depositos <- depositos[,c(1,19,20,21)]
names(depositos)[1] <- "Fecha"
names(depositos)[2] <- "M1"
names(depositos)[3] <- "M2"
names(depositos)[4] <- "M3"

depositos <- depositos %>% mutate(Fecha = ymd(Fecha)) %>%
  group_by(Fecha) %>%
  expand(Fecha = seq(floor_date(Fecha, unit = "week"),
       ceiling_date(Fecha, unit="week")-days(1), by="day"), M1,M2,M3) %>%
as.data.frame()

depositos <- depositos %>% filter(Fecha >= "2012-01-01" & Fecha <= "2017-12-31")

data <- full_join(datos,depositos,by="Fecha")
```

```{r}
#Dia de la semana
data$dia_semana <- weekdays(data$Fecha)

###Numero de la semana por mes
##monthweeks <- function(x) {
##    ceiling(as.numeric(format(x, "%d")) / 7)
##}
##data$numero_semana <- lapply(data$Fecha,monthweeks)
##
##data$Fecha <- as.Date(data$Fecha)
```


```{r}
###Dias festivos
##pascua <- function(x){#Dado un año retorna la fecha de la pascua.
##  #https://www.uv.es/sofuen/actividades/actividad4/fechadepascua.pdf
##  x <- as.numeric(x)
##  a <- x%%19
##  b <- x%%4
##  c <- x%%7
##  d <- (19*a + 24)%%30
##  e <- (2*b + 4*c + 6*d + 5)%%7
##  M <- 24
##  N <- 5
##  if((22+d+e) < 32){
##    return(as.Date(paste(as.character(x),"-03-",as.character((22+d+e)),sep = ##""),format="%Y-%m-%d"))
##  }
##  else{
##    return(as.Date(paste(as.character(x),"-04-",as.character(d+e-9),sep = ##""),format="%Y-%m-%d"))
##  }
##}
##
##mover_festivo <- function(x){ #Dada una fecha, mover el festivo a lunes.
##  dia_semana <- weekdays(x)
##  result = switch(  
##    dia_semana,  
##    "lunes"= x,
##    "martes"= x+6,  
##    "miércoles"= x+5,  
##    "jueves"= x+4,
##    "viernes"= x+3,
##    "sábado"= x+2,
##    "domingo"= x+1)
##  
##    
##  return(result)
##
##}
##
##festivo <- function(x){#Dada una fecha retornar si es festivo
##  
##  anio <- format(x,format = "%Y")
##  
##  festivos <- c(as.Date(format(paste(as.character(anio),"-01-01",sep = ""),format = ##"%Y-%m-%d")),
##                mover_festivo(as.Date(format(paste(as.character(anio),"-01-06",sep = ##""),format = "%Y-%m-%d"))),
##                mover_festivo(as.Date(format(paste(as.character(anio),"-03-19",sep = ##""),format = "%Y-%m-%d"))),
##                pascua(anio) - 3,
##                pascua(anio) - 2,
##                as.Date(format(paste(as.character(anio),"-05-01",sep = ""),format = ##"%Y-%m-%d")),
##                mover_festivo(pascua(anio)+40),
##                mover_festivo(pascua(anio)+60),
##                mover_festivo(as.Date(format(paste(as.character(anio),"-06-11",sep = ##""),format = "%Y-%m-%d"))),
##                mover_festivo(as.Date(format(paste(as.character(anio),"-06-29",sep = ##""),format = "%Y-%m-%d"))),
##                as.Date(format(paste(as.character(anio),"-07-20",sep = ""),format = ##"%Y-%m-%d")),
##                as.Date(format(paste(as.character(anio),"-08-07",sep = ""),format = ##"%Y-%m-%d")),
##                mover_festivo(as.Date(format(paste(as.character(anio),"-08-15",sep = ##""),format = "%Y-%m-%d"))),
##                mover_festivo(as.Date(format(paste(as.character(anio),"-10-12",sep = ##""),format = "%Y-%m-%d"))),
##                mover_festivo(as.Date(format(paste(as.character(anio),"-11-01",sep = ##""),format = "%Y-%m-%d"))),
##                mover_festivo(as.Date(format(paste(as.character(anio),"-11-11",sep = ##""),format = "%Y-%m-%d"))),
##                as.Date(format(paste(as.character(anio),"-12-08",sep = ""),format = ##"%Y-%m-%d")),
##                as.Date(format(paste(as.character(anio),"-12-25",sep = ""),format = ##"%Y-%m-%d")))
##  
##  
##  return(x %in% festivos)
##  
##  
##}
##
##
##data$feriado <- lapply(data$Fecha,festivo)

 
```

```{r}
#Tasa de desempleo
desempleo <- read_excel("archivos/Tasa_desempleo.xlsx", skip = 8)
desempleo <- desempleo[,c(1,3)]
names(desempleo)[1] <- "Fecha"
names(desempleo)[2] <- "tasa_desempleo"
desempleo$Fecha <- as.Date(paste(desempleo$Fecha,"-01",sep = ""),format = "%Y-%m-%d")

desempleo <- desempleo %>% mutate(Fecha = ymd(Fecha)) %>%
  group_by(Fecha) %>%
  expand(Fecha = seq(floor_date(Fecha, unit = "month"),
       ceiling_date(Fecha, unit="month")-days(1), by="day"), tasa_desempleo) %>%
as.data.frame()

desempleo <- desempleo %>% filter(Fecha >= "2012-01-01" & Fecha <= "2017-12-31")

data <- full_join(data,desempleo,by="Fecha")

```

```{r}
#Salario minimo
salario_minimo <- read_excel("archivos/Salario_minimo.xlsx", skip = 5)
salario_minimo <- salario_minimo[,c(1,3)]
names(salario_minimo)[1] <- "Fecha"
names(salario_minimo)[2] <- "salario"
salario_minimo$Fecha <- as.Date(paste(salario_minimo$Fecha,"-01-01",sep = ""),format = "%Y-%m-%d")
salario_minimo <- salario_minimo %>% mutate(Fecha = ymd(Fecha)) %>%
  group_by(Fecha) %>%
  expand(Fecha = seq(floor_date(Fecha, unit = "year"),
       ceiling_date(Fecha, unit="year")-days(1), by="day"), salario) %>%
as.data.frame()
salario_minimo <- salario_minimo %>% filter(Fecha >= "2012-01-01" & Fecha <= "2017-12-31")
data <- full_join(data,salario_minimo,by="Fecha")
```

```{r}
#Inflacion
inflacion <- read_excel("archivos/Inflacion.xlsx", skip = 7)
inflacion <- inflacion[,c(1,2)]
names(inflacion)[1] <- "Fecha"
names(inflacion)[2] <- "Inflacion"
inflacion$Fecha <- as.Date(paste(inflacion$Fecha,"-01",sep = ""),format = "%Y-%m-%d")
inflacion <- inflacion %>% mutate(Fecha = ymd(Fecha)) %>%
  group_by(Fecha) %>%
  expand(Fecha = seq(floor_date(Fecha, unit = "month"),
       ceiling_date(Fecha, unit="month")-days(1), by="day"), Inflacion) %>%
as.data.frame()
inflacion <- inflacion %>% filter(Fecha >= "2012-01-01" & Fecha <= "2017-12-31")
data <- full_join(data,inflacion,by="Fecha")
```

```{r}
#TRM Dolar
trm <- read_excel("archivos/Trm.xlsx", skip = 7)
names(trm)[1] <- "Fecha"
names(trm)[2] <- "Trm"
trm <- trm %>% filter(Fecha >= "2011-12-31" & Fecha <= "2017-12-31")
data <- full_join(data,trm,by="Fecha")

```

```{r message=FALSE}
#Icc
icc <- read_excel("archivos/ICC.xlsx")
icc <- icc[,c(1,2)]
names(icc)[1] <- "Fecha"
names(icc)[2] <- "icc"
#icc$Fecha <- as.Date(paste(icc$Fecha,"-01",sep = ""),format = "%Y-%m-%d")
icc <- icc %>% mutate(Fecha = ymd(Fecha)) %>%
  group_by(Fecha) %>%
  expand(Fecha = seq(floor_date(Fecha, unit = "month"),
       ceiling_date(Fecha, unit="month")-days(1), by="day"), icc) %>%
as.data.frame()
icc <- icc %>% filter(Fecha >= "2012-01-01" & Fecha <= "2017-12-31")
data <- full_join(data,icc,by="Fecha")
```

###La base de datos final se llama data.
```{r}
write.table(data, "datos2012_2017", sep="\t")
```

```{r}
library(fitdistrplus)          ##Paquete para ajustar distribuciones a los datos
attach(data)
descdist(Unidades, discrete = FALSE) ##Función para encontrar mejor ajuste
```


```{r}
distribucion <- fitdist(Unidades, "norm") ##Ajustando los datos a una distribución normal
plot(distribucion) ##Chequeo gráfico del ajuste
```

## Modelo Aditivo Generalizado (GAM) repuesta tipo Poisson 

```{r}
library(mgcv)
mod1 <- gam(Unidades ~ anio + s(mes) + s(dia) + s(M3) + dia_semana + s(tasa_desempleo) + s(Trm) + s(icc), family = poisson(link = "log"), data = data)

summary(mod1)
```

### Modelo Lineal Generalizado con repuesta tipo Poisson
```{r, message=FALSE}
library(rsq)
mod2 <- glm(Unidades ~ anio + mes + dia + M3 + dia_semana + tasa_desempleo + Trm + icc, family = poisson(link = "log"), data = data)
summary(mod2)
rsq(mod2, adj = TRUE)
```

```{r}
library(readxl)
consultas <- read_excel("Archivos/consultas.xlsx")
data <- as.data.frame(cbind(data, consultas))
```

## Modelo Aditivo Generalizado (GAM) repuesta tipo Poisson 

```{r, message=FALSE}
library(mgcv)
attach(data)
mod3 <- gam(Unidades ~ s(mes) + s(dia) + s(M3) + dia_semana + s(tasa_desempleo) + s(Trm) + s(icc) + s(tu_carro) + s(revista_motor) + s(carroya) + s(unidades_vendidasalmes) + feriado + s(numero_semana) + s(importaciones), family = poisson(link = "log"), data = data)

summary(mod3)
```

## Modelo Aditivo Generalizado (GAM) repuesta tipo Poisson 

```{r}
library(mgcv)

mod4 <- gam(Unidades ~ anio + s(mes) + s(dia) + s(M3) + dia_semana + s(tasa_desempleo) + s(Trm) + s(icc) + s(tu_carro) + s(revista_motor) + s(carroya) + s(unidades_vendidasalmes) + feriado + s(numero_semana) + s(importaciones) + s(vehiculos)+ s(incremento_gasolina), family = poisson(link = "log"), data = data)

summary(mod4)
```

## Modelo Aditivo Generalizado (GAM) repuesta tipo Normal 

```{r}
library(mgcv)

mod5 <- gam(Unidades ~ anio + s(mes) + s(dia) + s(M3) + dia_semana + s(tasa_desempleo) + s(Trm) + s(icc) + s(tu_carro) + s(revista_motor) + s(carroya) + s(unidades_vendidasalmes) + feriado + s(numero_semana) + s(importaciones) + s(vehiculos), family = gaussian(link = "identity"), data = data)

summary(mod5)
```

